// Generated by CoffeeScript 1.9.1
var Gaze, exec, gaze;

exec = require('child_process').exec;

Gaze = require('gaze').Gaze;

gaze = new Gaze([__dirname + '/*.cjsx']);

gaze.on('ready', function(watcher) {
  return console.log('start watching...');
});

gaze.on('all', function(event, filepath) {
  console.log("event: " + event);
  console.log("file: " + filepath);
  console.log("timestamp: " + (new Date()));
  console.log('');
  return exec("cjsx -o " + __dirname + "/../ -cb " + filepath, function(error, stdout, stderr) {
    if (stdout) {
      console.log(stdout);
    }
    if (stderr) {
      console.error(stderr);
    }
    if (error != null) {
      console.error("exec error: " + error);
    }
    return console.log('########################## done #############################');
  });
});
